import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ThemeProvider, ThemeToggle } from "~/components/theme-provider";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  navigationMenuTriggerStyle,
} from "~/components/ui/navigation-menu";
import Link from "next/link";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const basePath = process.env.NODE_ENV === "production" ? "/TerMinable" : "";

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <ThemeProvider className="bg-gradient-to-b from-[var(--primary)] to-[var(--background)] dark:from-[var(--background)] dark:to-[var(--primary-foreground)]">
        <nav className="fixed left-0 right-0 top-0 bg-white/10 p-4 backdrop-blur-md">
          <div className="mx-auto max-w-7xl">
            <NavigationMenu>
              <NavigationMenuList className="flex justify-center">
                <NavigationMenuItem>
                  <NavigationMenuLink
                    href={`${basePath}/`}
                    className={`${navigationMenuTriggerStyle()} text-gray-900 hover:text-gray-700 dark:text-white dark:hover:text-gray-300`}
                  >
                    Home
                  </NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink
                    href={`${basePath}/docs`}
                    className={`${navigationMenuTriggerStyle()} text-gray-900 hover:text-gray-700 dark:text-white dark:hover:text-gray-300`}
                  >
                    Docs
                  </NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <ThemeToggle />
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
          </div>
        </nav>
        <div className="mc pt-12">
          {children}
          <footer className="bottom-0 left-0 right-0 p-4 pb-8 pt-8 backdrop-blur-md">
            <div className="mx-auto max-w-7xl">
              <p className="text-gray-900 dark:text-white">
                Site built with{" "}
                <Link href="https://butt3r.dev" className="text-primary">
                  ButT3r
                </Link>
              </p>
            </div>
          </footer>
        </div>
      </ThemeProvider>
    </html>
  );
}
