import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ThemeProvider, ThemeToggle } from "~/components/theme-provider";
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  navigationMenuTriggerStyle,
} from "~/components/ui/navigation-menu";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <ThemeProvider className="bg-gradient-to-b from-[var(--primary)] to-[var(--background)] dark:from-[var(--background)] dark:to-[var(--primary-foreground)]">
        <nav className="fixed left-0 right-0 top-0 bg-white/10 p-4 backdrop-blur-md">
          <div className="max-w-7xl mx-auto">
            <NavigationMenu>
              <NavigationMenuList className="flex justify-center">
                <NavigationMenuItem>
                  <NavigationMenuLink href="/" className={`${navigationMenuTriggerStyle()} text-gray-900 hover:text-gray-700 dark:text-white dark:hover:text-gray-300`}>Home</NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <NavigationMenuLink href="/docs" className={`${navigationMenuTriggerStyle()} text-gray-900 hover:text-gray-700 dark:text-white dark:hover:text-gray-300`}>Docs</NavigationMenuLink>
                </NavigationMenuItem>
                <NavigationMenuItem>
                  <ThemeToggle />
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
          </div>
        </nav>
        <div className="mc">{children}</div>
      </ThemeProvider>
    </html>
  );
}
